### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by JessWallace94** [hack101/lesson2#1]
Sorry to be a pain - you've mentioned the use of CSS, but not dived too much into it - although styling isn't the most important part - in web applications, design is important - wondered if you could expand more on CSS or create CSS lessons?

**Comment by Akollek** [comment]
Hi Jess - design is indeed important. Thanks for suggesting we do more on CSS, we'll keep that in mind for any future tutorials we write! That may not be for a while, so in the meantime there are a bunch of good CSS tutorials online. W3Schools has a thorough one: http://www.w3schools.com/css/
